# Generated by Django 2.2.24 on 2021-09-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='student.png', null=True, upload_to='profile_pic/Customer/'),
        ),
    ]
