# Generated by Django 2.2.24 on 2021-09-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210917_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/customer.png', null=True, upload_to='profile_pic/Customer/'),
        ),
    ]
