# Generated by Django 3.2.8 on 2021-10-23 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0002_rename_proudct_product'),
        ('customer', '0005_auto_20210917_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('qntt', models.PositiveIntegerField(default=1)),
                ('fullName', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('orderedDate', models.DateField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(default='Deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='admn.product')),
            ],
        ),
    ]
