# Generated by Django 3.2.7 on 2021-09-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proudct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('desc', models.CharField(max_length=60)),
                ('img', models.ImageField(blank=True, default='product/default.png', null=True, upload_to='product/')),
            ],
        ),
    ]
