# Generated by Django 3.2.7 on 2021-09-23 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='proudct',
            new_name='product',
        ),
    ]
