# Generated by Django 3.2.8 on 2021-10-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0003_auto_20211023_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='product_category',
        ),
    ]
