# Generated by Django 3.2.8 on 2021-10-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0004_rename_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productCategory',
        ),
    ]
