# Generated by Django 3.2.8 on 2021-10-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0005_remove_product_productcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_category',
        ),
    ]
