# Generated by Django 3.2.8 on 2021-10-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admn', '0007_auto_20211023_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productCategory',
        ),
        migrations.DeleteModel(
            name='product_category',
        ),
    ]
